/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihsan.ihsan_view;

//import ihsan.ihsan_view.ViewLogin;
//import ihsan_view.ViewBarangInternal;
//import ihsan_view.ViewDataUser;
//import ihsan.ihsan_view.ViewHistoriTransaksi;
//import ihsan_view.ViewInternalKaryawan;
//import ihsan_view.ViewListDataPelanggan;
//import ihsan_view.ViewPelangganInternal;
//import ihsan_view.ViewTransaksi;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author user
 */
public class AppUtama extends javax.swing.JFrame {

    /**
     * Creates new form AppUtama
     */
    public AppUtama() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        try {
    UIManager.setLookAndFeel(new NimbusLookAndFeel());
    UIManager.put("control", new Color(128, 128, 128));
    UIManager.put("info", new Color(128, 128, 128));
    UIManager.put("nimbusBase", new Color(18, 30, 49));
    UIManager.put("nimbusAlertYellow", new Color(248, 187, 0));
    UIManager.put("nimbusDisabledText", new Color(128, 128, 128));
    UIManager.put("nimbusFocus", new Color(115, 164, 209));
    UIManager.put("nimbusGreen", new Color(176, 179, 50));
    UIManager.put("nimbusInfoBlue", new Color(66, 139, 221));
    UIManager.put("nimbusLightBackground", new Color(18, 30, 49));
    UIManager.put("nimbusOrange", new Color(191, 98, 4));
    UIManager.put("nimbusRed", new Color(169, 46, 34));
    UIManager.put("nimbusSelectedText", new Color(255, 255, 255));
    UIManager.put("nimbusSelectionBackground", new Color(104, 93, 156));
    UIManager.put("text", new Color(230, 230, 230));
    SwingUtilities.updateComponentTreeUI(this);
} catch (UnsupportedLookAndFeelException exc) {
    System.err.println("Nimbus: Unsupported Look and feel!");
}
    }

    public JMenuItem getMasterBarang() {
        return masterBarang;
    }

    public JMenuItem getMasterPelanggan() {
        return masterPelanggan;
    }

    public JMenuItem getMasterTransaksi() {
        return masterTransaksi;
    }

    public JMenuItem getMasterUserProgram() {
        return masterUserProgram;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopUtama = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        masterPelanggan = new javax.swing.JMenuItem();
        masterBarang = new javax.swing.JMenuItem();
        masterTransaksi = new javax.swing.JMenuItem();
        masterUserProgram = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        transaksiPOS = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Program Point of Sales");

        desktopUtama.setAutoscrolls(true);

        javax.swing.GroupLayout desktopUtamaLayout = new javax.swing.GroupLayout(desktopUtama);
        desktopUtama.setLayout(desktopUtamaLayout);
        desktopUtamaLayout.setHorizontalGroup(
            desktopUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );
        desktopUtamaLayout.setVerticalGroup(
            desktopUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Program Point of Sales");

        jMenu2.setText("Master");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        masterPelanggan.setText("Master Pelanggan");
        masterPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterPelangganActionPerformed(evt);
            }
        });
        jMenu2.add(masterPelanggan);

        masterBarang.setText("Master Barang");
        masterBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterBarangMouseClicked(evt);
            }
        });
        masterBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterBarangActionPerformed(evt);
            }
        });
        jMenu2.add(masterBarang);

        masterTransaksi.setText("Master Transaksi");
        masterTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterTransaksiActionPerformed(evt);
            }
        });
        jMenu2.add(masterTransaksi);

        masterUserProgram.setText("Master User Program");
        masterUserProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterUserProgramActionPerformed(evt);
            }
        });
        jMenu2.add(masterUserProgram);

        jMenuItem1.setText("Master Karyawan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        menuTransaksi.setText("Transaksi Barang");
        menuTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTransaksiMouseClicked(evt);
            }
        });
        menuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiActionPerformed(evt);
            }
        });

        transaksiPOS.setText("Transaksi (POS)");
        transaksiPOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiPOSMouseClicked(evt);
            }
        });
        transaksiPOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiPOSActionPerformed(evt);
            }
        });
        menuTransaksi.add(transaksiPOS);

        jMenuBar1.add(menuTransaksi);

        jMenu1.setText("Logout");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desktopUtama, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desktopUtama)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

    }//GEN-LAST:event_jMenu2MouseClicked

    private void masterPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterPelangganActionPerformed
ViewPelangganInternal vpm = new ViewPelangganInternal();
        this.desktopUtama.add(vpm);
        vpm.show();    }//GEN-LAST:event_masterPelangganActionPerformed

    private void masterBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterBarangActionPerformed
        
        ViewBarangInternal vBI = new ViewBarangInternal();
        this.desktopUtama.add(vBI);
        vBI.show();
    }//GEN-LAST:event_masterBarangActionPerformed

    private void masterBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterBarangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masterBarangMouseClicked

    private void menuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiActionPerformed

    }//GEN-LAST:event_menuTransaksiActionPerformed

    private void menuTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTransaksiMouseClicked

    }//GEN-LAST:event_menuTransaksiMouseClicked

    private void transaksiPOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiPOSActionPerformed
        ViewTransaksi vT = new ViewTransaksi();
        this.desktopUtama.add(vT);
        vT.show();
    }//GEN-LAST:event_transaksiPOSActionPerformed

    private void transaksiPOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiPOSMouseClicked

    }//GEN-LAST:event_transaksiPOSMouseClicked

    private void masterTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterTransaksiActionPerformed
        // TODO add your handling code here:
        ViewHistoriTransaksi vHT = new ViewHistoriTransaksi();
        this.desktopUtama.add(vHT);
        vHT.show();       // TODO add your handling code here:
    }//GEN-LAST:event_masterTransaksiActionPerformed

    private void masterUserProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterUserProgramActionPerformed
        // TODO add your handling code here:
        ViewDataUser vDU = new ViewDataUser();
        this.desktopUtama.add(vDU);
        vDU.show();
    }//GEN-LAST:event_masterUserProgramActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
      new ViewLogin().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
              new ViewLogin().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ViewInternalKaryawan vIK = new ViewInternalKaryawan();
        this.desktopUtama.add(vIK);
        vIK.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AppUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AppUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AppUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AppUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//       
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AppUtama().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem masterBarang;
    private javax.swing.JMenuItem masterPelanggan;
    private javax.swing.JMenuItem masterTransaksi;
    private javax.swing.JMenuItem masterUserProgram;
    private javax.swing.JMenu menuTransaksi;
    private javax.swing.JMenuItem transaksiPOS;
    // End of variables declaration//GEN-END:variables
}
