/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihsan.ihsan_view;

import com.mysql.cj.xdevapi.Result;
import ihsan.ihsan_database.db.KonfigurasiDatabase;
import ihsan.ihsan_controller.ControllerUser;
import ihsan.ihsan_controller.ControllerPelanggan;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ViewDataUser extends javax.swing.JInternalFrame  {

    private ControllerUser cU;
    private DefaultTableModel model;

    public ViewDataUser() {
        initComponents();
        cU = new ControllerUser(this);
        model = new DefaultTableModel();
        tabelUser.setModel(model);
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Level Akses");
        
        tampilDataUser();
        cU.kontrolButton();
   
    }

    public boolean getAdminRB() {
        return adminRB.isSelected();
    }
    
    public void setLevelAkses(String levelAkses) {
        if(levelAkses.equals("karyawan")){
            karyawanRB.setSelected(true);
            adminRB.setSelected(false);}
            else{
            adminRB.setSelected(true);
            karyawanRB.setSelected(false);
    }
    }

    

    public boolean getKaryawanRB() {
        return karyawanRB.isSelected();
    }

    public String getPasswordTF() {
        return passwordTF.getText();
    }

    public void setPasswordTF(String password) {
       passwordTF.setText(password);
    }

    public String getUsernameTF() {
        return usernameTFF.getText();
    }

    public void setUsernameTF(String usernameTF) {
       usernameTFF.setText(usernameTF);
    }

    public JButton getBatalButton() {
        return batalButton;
    }

    public JButton getHapusButton() {
        return hapusButton;
    }

    public JButton getSimpanButton() {
        return simpanButton;
    }

    public JButton getUbahButton() {
        return ubahButton;
    }
   
    
    
    public void refreshTable() {
        tampilDataUser();
    }
    
    private void tampilDataUser() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        String sql = "SELECT * from users";
        
        try {
            Statement stat = (Statement) KonfigurasiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()) {
                Object[] hasil;
                hasil = new Object[7];
                hasil[0] = res.getString("username");
                hasil[1] = res.getString("password");
                hasil[2] = res.getString("levelAkses");
                
//                System.out.print("Print:" + hasil);

                model.addRow(hasil);
        }
        } catch (SQLException ex) {
            System.err.print("gagal eksekusi:" + ex);
        }
       
       
        
    }
        private void ambilDataTabel() {
        int index = tabelUser.getSelectedRow();
        String username = String.valueOf(tabelUser.getValueAt(index, 0));
        String password = String.valueOf(tabelUser.getValueAt(index, 1));
        String levelAkses = String.valueOf(tabelUser.getValueAt(index, 2));
        
        usernameTFF.setText(username);
        passwordTF.setText(password);
        if(levelAkses.equals("A")) {
        adminRB.setSelected(true);
        karyawanRB.setSelected(false);
        } else {
            karyawanRB.setSelected(true);
            adminRB.setSelected(false);
        }
        
       cU.kontrolButton2();
        
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        namaPelangganTxt = new javax.swing.JLabel();
        noHpTxt = new javax.swing.JLabel();
        simpanButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hapusButton = new javax.swing.JButton();
        ubahButton = new javax.swing.JButton();
        batalButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelUser = new javax.swing.JTable();
        passwordTF = new javax.swing.JPasswordField();
        karyawanRB = new javax.swing.JRadioButton();
        adminRB = new javax.swing.JRadioButton();
        usernameTFF = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);

        namaPelangganTxt.setText("Password:");

        noHpTxt.setText("Level Akses:");

        simpanButton.setText("SIMPAN");
        simpanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("Username:");

        hapusButton.setText("HAPUS");
        hapusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusButtonMouseClicked(evt);
            }
        });

        ubahButton.setText("UBAH");
        ubahButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahButtonMouseClicked(evt);
            }
        });
        ubahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahButtonActionPerformed(evt);
            }
        });

        batalButton.setText("BATAL");
        batalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batalButtonMouseClicked(evt);
            }
        });
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });

        tabelUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelUser.setFillsViewportHeight(true);
        tabelUser.setRowHeight(50);
        tabelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelUser);

        buttonGroup1.add(karyawanRB);
        karyawanRB.setText("Karyawan");

        buttonGroup1.add(adminRB);
        adminRB.setText("Admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noHpTxt)
                            .addComponent(namaPelangganTxt)
                            .addComponent(jLabel1))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(passwordTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(adminRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(karyawanRB))
                            .addComponent(usernameTFF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(batalButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ubahButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(simpanButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameTFF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaPelangganTxt)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noHpTxt)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adminRB)
                        .addComponent(karyawanRB)))
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batalButton)
                    .addComponent(hapusButton)
                    .addComponent(ubahButton)
                    .addComponent(simpanButton))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanButtonMouseClicked
        if(usernameTFF.getText().isBlank() || passwordTF.getText().isBlank() || (adminRB.isSelected() == false && karyawanRB.isSelected() == false)) {
            JOptionPane.showMessageDialog(this, "Semua kolom wajib diisi!");
            return;
        }   
        cU.simpan(); 
    }//GEN-LAST:event_simpanButtonMouseClicked

    private void hapusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusButtonMouseClicked
        cU.hapus();       
    }//GEN-LAST:event_hapusButtonMouseClicked

    private void ubahButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahButtonMouseClicked
        if(usernameTFF.getText().isBlank() || passwordTF.getText().isBlank() || (adminRB.isSelected() == false && karyawanRB.isSelected() == false)) {
            JOptionPane.showMessageDialog(this, "Semua kolom wajib diisi!");
            return;
        }      
        cU.ubah();
    }//GEN-LAST:event_ubahButtonMouseClicked

    private void ubahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahButtonActionPerformed

    private void batalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batalButtonMouseClicked
        cU.kontrolButton();
        cU.bersihkan();
    }//GEN-LAST:event_batalButtonMouseClicked

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batalButtonActionPerformed

    private void tabelUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelUserMouseClicked
        ambilDataTabel();
    }//GEN-LAST:event_tabelUserMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewPelangganInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewPelangganInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewPelangganInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewPelangganInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewPelangganInternal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminRB;
    private javax.swing.JButton batalButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton karyawanRB;
    private javax.swing.JLabel namaPelangganTxt;
    private javax.swing.JLabel noHpTxt;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTable tabelUser;
    private javax.swing.JButton ubahButton;
    private javax.swing.JTextField usernameTFF;
    // End of variables declaration//GEN-END:variables
}
