/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihsan.ihsan_view;

import ihsan.ihsan_database.db.KonfigurasiDatabase;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ViewListDataPelanggan extends javax.swing.JFrame {

    private ViewTransaksi vT;
    private DefaultTableModel model;
    private String sql = "";
    public ViewListDataPelanggan(ViewTransaksi vT) {
        initComponents();
        
        this.vT = vT;
        model = new DefaultTableModel();
        viewListDataPelangganTabel.setModel(model);
        model.addColumn("ID Pelanggan");
        model.addColumn("Nama Pelanggan");
        model.addColumn("No. HP");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Usia");
        model.addColumn("Alamat");
        tampilDataPelanggan();
        
    }
    
    private void tampilDataPelanggan() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        sql = "SELECT * from pelanggan";
        
        try {
            Statement stat = (Statement) KonfigurasiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()) {
                Object[] hasil;
                hasil = new Object[7];
                hasil[0] = Integer.toString(res.getInt("id"));
                hasil[1] = res.getString("namaPelanggan");
                hasil[2] = res.getString("noHp");
                hasil[3] = res.getString("jenisKelamin");
                hasil[4] = Integer.toString(res.getInt("umur"));
                hasil[5] = res.getString("alamat");
                
                model.addRow(hasil);
        }
        } catch (SQLException ex) {
            System.err.print("gagal eksekusi:" + ex.getErrorCode());
        }
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewListDataPelangganTabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("List Data Pelanggan");

        viewListDataPelangganTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        viewListDataPelangganTabel.setRowHeight(50);
        viewListDataPelangganTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewListDataPelangganTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(viewListDataPelangganTabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewListDataPelangganTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewListDataPelangganTabelMouseClicked
        int listX = viewListDataPelangganTabel.getSelectedRow();
        vT.getIdPelanggan().setText(viewListDataPelangganTabel.getValueAt(listX,0).toString());
        vT.getNamaPelanggan().setText(viewListDataPelangganTabel.getValueAt(listX,1).toString());
        vT.getNoHpPelanggan().setText(viewListDataPelangganTabel.getValueAt(listX,2).toString());
        vT.getJenisKelaminPelanggan().setText(viewListDataPelangganTabel.getValueAt(listX,3).toString());
        vT.getAlamatPelanggan().setText(viewListDataPelangganTabel.getValueAt(listX,4).toString());
        this.dispose();                
    }//GEN-LAST:event_viewListDataPelangganTabelMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewListDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewListDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewListDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewListDataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
////                new ViewListDataPelanggan().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable viewListDataPelangganTabel;
    // End of variables declaration//GEN-END:variables
}
