/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ihsan.ihsan_view;

import ihsan.ihsan_database.db.KonfigurasiDatabase;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ViewListDataBarang extends javax.swing.JFrame {

   
   private ViewTransaksi vT;
   private DefaultTableModel model;
   private String sql = "";
   
    public ViewListDataBarang(ViewTransaksi vT) {
        initComponents();
        
        this.vT = vT;
        model = new DefaultTableModel();
        tabelDataBarang.setModel(model);
        model.addColumn("ID Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Satuan Barang");
        model.addColumn("Jenis Barang");
        model.addColumn("Ukuran");
        model.addColumn("Harga");
        tampilDataBarang("");

    }
    
    private void tampilDataBarang(String data) {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        if(data.equals("")) 
           sql = "SELECT * from barang";
        else 
            sql = "SELECT * FROM barang WHERE namaBarang LIKE '"+data+"%'";

       try {
           Statement stmt = (Statement) KonfigurasiDatabase.getKoneksi().createStatement();
           ResultSet res = stmt.executeQuery(sql);
           
           while(res.next()) {
               Object[] hasil;
               hasil = new Object[6];
               
               hasil[0] = res.getString("idBarang");
               hasil[1] = res.getString("namaBarang");
               hasil[2] = res.getString("jenisBarang");
               hasil[3] = res.getString("satuan");
               hasil[4] = res.getString("ukuran");
               hasil[5] = res.getString("harga");
               
               model.addRow(hasil);
               
               
           }
           
       } catch (SQLException ex) {
           System.err.print("Error tidak bisa mengeksekusi:" + ex);
       }
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cariNamaBarangTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataBarang = new javax.swing.JTable();

        setTitle("List Data Barang");

        jLabel2.setText("Cari Nama Barang");

        cariNamaBarangTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariNamaBarangTFKeyPressed(evt);
            }
        });

        tabelDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDataBarang.setRowHeight(50);
        tabelDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataBarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cariNamaBarangTF, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cariNamaBarangTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariNamaBarangTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariNamaBarangTFKeyPressed
       tampilDataBarang(cariNamaBarangTF.getText());
    }//GEN-LAST:event_cariNamaBarangTFKeyPressed

    private void tabelDataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataBarangMouseClicked
        int ambilRow  = tabelDataBarang.getSelectedRow();
        
        vT.getNamaBarangTF().setText(tabelDataBarang.getValueAt(ambilRow, 1).toString());
        vT.getHargaBarangTF().setText(tabelDataBarang.getValueAt(ambilRow, 5).toString());
        vT.getIdBarangTF().setText(tabelDataBarang.getValueAt(ambilRow, 0).toString());
        vT.getHargaBarangTF().requestFocus();
        this.dispose();
    }//GEN-LAST:event_tabelDataBarangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cariNamaBarangTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDataBarang;
    // End of variables declaration//GEN-END:variables
}
