/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ihsan.ihsan_view;
import ihsan.ihsan_database.db.KonfigurasiDatabase;
import ihsan.ihsan_controller.ControllerTransaksi;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class ViewTransaksi extends javax.swing.JInternalFrame {

    private DefaultTableModel model;
    private ControllerTransaksi cT;
    Vector hasilTambahBarang = new Vector();
    /**
     * Creates new form ViewTransaksi
     */
   
    
    public ViewTransaksi() {
        initComponents();
        model = new DefaultTableModel();
        tabelTransaksi.setModel(model);
        model.addColumn("Nama Barang");
        model.addColumn("ID Barang");
        model.addColumn("Harga Barang");
        model.addColumn("Kuantitas Barang");
        model.addColumn("Subtotal");
        


        cT = new ControllerTransaksi(this);

        
    }

    public JTextField getAlamatPelanggan() {
        return alamatPelanggan;
    }

    public JTextField getIdPelanggan() {
        return idPelanggan;
    }
    
    public void setHasilTambahBarangClear() {
        hasilTambahBarang.clear();
    }
    
    public void setHasilTambahBarang(String set) {
        hasilTambahBarang.add(set);
    }
    
    public Vector getHasilTambahBarang() {
        return hasilTambahBarang;
    }

    public JTextField getJenisKelaminPelanggan() {
        return jenisKelaminPelanggan;
    }

    public JTextField getNamaPelanggan() {
        return namaPelanggan;
    }

    public JTextField getNoHpPelanggan() {
        return noHpPelanggan;
    }

    public JTextField getNamaBarangTF() {
        return namaBarangTF;
    }

    public JSpinner getQtyBeliTF() {
        return qtyBeliTF;
    }
    
    public JTextField getHargaBarangTF() {
        return hargaBarangTF;
    }

    public JTextField getTotalBayarTF() {
        return totalBayarTF;
    }

    public JTextField getUangBayarTF() {
        return uangBayarTF;
    }

    public JTextField getIdBarangTF() {
        return idBarangTF;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idPelanggan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namaPelanggan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        alamatPelanggan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        noHpPelanggan = new javax.swing.JTextField();
        jenisKelaminPelanggan = new javax.swing.JTextField();
        cariDataPelangganBT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        namaBarangTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tambahBarangBT = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        hargaBarangTF = new javax.swing.JTextField();
        idBarangTF = new javax.swing.JTextField();
        jofewfwrw = new javax.swing.JLabel();
        qtyBeliTF = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        totalBayarTF = new javax.swing.JTextField();
        uangBayarTF = new javax.swing.JTextField();
        prosesTransaksiBT = new javax.swing.JButton();
        batalTransaksiBT = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Form Transaksi");
        setAutoscrolls(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("Form Transaksi Barang");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pelanggan - Pembelian"));

        jLabel2.setText("Id Pelanggan");

        idPelanggan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        idPelanggan.setEnabled(false);

        jLabel3.setText("Nama Pelanggan");

        namaPelanggan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        namaPelanggan.setEnabled(false);
        namaPelanggan.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        namaPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namaPelangganKeyPressed(evt);
            }
        });

        jLabel4.setText("Alamat Pelanggan");

        alamatPelanggan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        alamatPelanggan.setEnabled(false);

        jLabel5.setText("Nomor HP");

        jLabel6.setText("Jenis Kelamin");

        noHpPelanggan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        noHpPelanggan.setEnabled(false);

        jenisKelaminPelanggan.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jenisKelaminPelanggan.setEnabled(false);

        cariDataPelangganBT.setText("Cari Data Pelanggan");
        cariDataPelangganBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cariDataPelangganBTMouseClicked(evt);
            }
        });
        cariDataPelangganBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariDataPelangganBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(alamatPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(idPelanggan))))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jenisKelaminPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noHpPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cariDataPelangganBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(noHpPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jenisKelaminPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(alamatPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariDataPelangganBT)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Barang - Transaksi"));

        namaBarangTF.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        namaBarangTF.setEnabled(false);
        namaBarangTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namaBarangTFFocusGained(evt);
            }
        });
        namaBarangTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namaBarangTFMouseClicked(evt);
            }
        });

        jLabel7.setText("Nama Barang");

        jLabel8.setText("Qty Beli");

        tambahBarangBT.setText("Tambah Barang");
        tambahBarangBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahBarangBTMouseClicked(evt);
            }
        });
        tambahBarangBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBarangBTActionPerformed(evt);
            }
        });

        jLabel11.setText("Harga Barang");

        hargaBarangTF.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        hargaBarangTF.setEnabled(false);

        idBarangTF.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        idBarangTF.setEnabled(false);

        jofewfwrw.setText("ID Barang");

        qtyBeliTF.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jofewfwrw)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hargaBarangTF, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(namaBarangTF)
                    .addComponent(idBarangTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(40, 40, 40)
                        .addComponent(qtyBeliTF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tambahBarangBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(namaBarangTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(qtyBeliTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(hargaBarangTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tambahBarangBT)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idBarangTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jofewfwrw))))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel9.setText("Total Bayar");

        jLabel10.setText("Uang Bayar");

        totalBayarTF.setText("0");
        totalBayarTF.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        totalBayarTF.setEnabled(false);
        totalBayarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBayarTFActionPerformed(evt);
            }
        });

        prosesTransaksiBT.setText("PROSES TRANSAKSI");
        prosesTransaksiBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prosesTransaksiBTMouseClicked(evt);
            }
        });
        prosesTransaksiBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesTransaksiBTActionPerformed(evt);
            }
        });

        batalTransaksiBT.setText("BATAL TRANSAKSI");
        batalTransaksiBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batalTransaksiBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                batalTransaksiBTMouseEntered(evt);
            }
        });
        batalTransaksiBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalTransaksiBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalBayarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uangBayarTF)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(batalTransaksiBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prosesTransaksiBT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(totalBayarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(uangBayarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(batalTransaksiBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prosesTransaksiBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTransaksi.setFillsViewportHeight(true);
        tabelTransaksi.setRowHeight(50);
        jScrollPane2.setViewportView(tabelTransaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(216, 216, 216)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // event maximize icon
    
    private void cariDataPelangganBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariDataPelangganBTMouseClicked
//        ViewListDataPelanggan vLDP = new ViewListDataPelanggan(this);
//        vLDP.setVisible(true);
    }//GEN-LAST:event_cariDataPelangganBTMouseClicked

    private void prosesTransaksiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesTransaksiBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prosesTransaksiBTActionPerformed

    private void namaBarangTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaBarangTFFocusGained
        ViewListDataBarang vIB = new ViewListDataBarang(this);
        vIB.setVisible(true);
        
    }//GEN-LAST:event_namaBarangTFFocusGained

    private void namaBarangTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaBarangTFMouseClicked
        ViewListDataBarang vIB = new ViewListDataBarang(this);
        vIB.setVisible(true);
    }//GEN-LAST:event_namaBarangTFMouseClicked

    private void tambahBarangBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahBarangBTMouseClicked
        // TODO add your handling code here:
if(idPelanggan.getText().isBlank() || namaPelanggan.getText().isBlank() || alamatPelanggan.getText().isBlank() || noHpPelanggan.getText().isBlank() ||
           jenisKelaminPelanggan.getText().isBlank() || namaBarangTF.getText().isBlank() || hargaBarangTF.getText().isBlank() || idBarangTF.getText().isBlank() ||
           qtyBeliTF.getValue().equals(0)) {
    JOptionPane.showMessageDialog(this, "Silakan isi semua kolom!");
    return;
}
        Object[] hasil;
        hasil = new Object[7];          
        hasil[0] = namaBarangTF.getText();
        hasil[1] = idBarangTF.getText();
        hasil[2] = hargaBarangTF.getText();
        hasil[3] = qtyBeliTF.getValue();
        hasil[4] = Integer.parseInt(hasil[2].toString()) * Integer.parseInt(hasil[3].toString());
//      model.addRow(hasil);
        int jumlahRow =   model.getRowCount();
        if(jumlahRow > 0) {
        for(int x = 0; x < jumlahRow; x++) {
            String kolomNamaBarang = tabelTransaksi.getValueAt(x, 0).toString();
            String kolomIdBarang = tabelTransaksi.getValueAt(x, 1).toString();
            int kolomHarga = Integer.parseInt(tabelTransaksi.getValueAt(x, 2).toString());
            int kolomQty = Integer.parseInt(tabelTransaksi.getValueAt(x, 3).toString());
            int kolomSubtotal = Integer.parseInt(tabelTransaksi.getValueAt(x, 4).toString());
            if(kolomNamaBarang.equals(hasil[0]) && kolomIdBarang.equals(hasil[1]) && kolomHarga == Integer.parseInt(hasil[2].toString())) {
               int kolomQtyUpdate = kolomQty + (Integer) hasil[3];
               int kolomSubtotalUpdate = kolomSubtotal + (Integer) hasil[4];
                
               tabelTransaksi.setValueAt(kolomQtyUpdate, x, 3);
               tabelTransaksi.setValueAt( kolomSubtotalUpdate,x, 4);
               
               int total = 0;
               for(int index = 0; index < jumlahRow; index++)  {
                int subtotal = Integer.parseInt(tabelTransaksi.getValueAt(index,4).toString());
                total += subtotal;
                        

            }
            totalBayarTF.setText(String.valueOf(total));
               return;
        }
        }
        }
        model.addRow(hasil);

        
        Integer total = 0;
        if(Integer.parseInt(totalBayarTF.getText()) == 0) {
            int subtotal = Integer.parseInt(tabelTransaksi.getValueAt(0, 4).toString());
            total = subtotal;
        } else{
            for(int index = 0; index < model.getRowCount(); index++)  {
                int subtotal = Integer.parseInt(tabelTransaksi.getValueAt(index,4).toString());
                total += subtotal;
            }
            
            
        }
        totalBayarTF.setText(String.valueOf(total));
        cariDataPelangganBT.setEnabled(false);
//        setHasilTambahBarangClear();
  
    }//GEN-LAST:event_tambahBarangBTMouseClicked

    private void prosesTransaksiBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prosesTransaksiBTMouseClicked
        // TODO add your handling code here:   
    String regex = "[0-9]+";
    if(!uangBayarTF.getText().matches(regex)) {
        JOptionPane.showMessageDialog(this, "Masukkan nominal pada kolom Uang Bayar!");
        return;
        
    }
        if(tabelTransaksi.getRowCount() == 0) {
           JOptionPane.showMessageDialog(this, "Silakan tambahkan barang!");
            return ;            
        }
        if(totalBayarTF.getText().isBlank() || uangBayarTF.getText().isBlank()) {
           JOptionPane.showMessageDialog(this, "Silakan isi kolom Uang Bayar!");
            return ;
    }        
        int idTransaksi = cT.simpanTransaksi();
        int jumlahRow =   tabelTransaksi.getRowCount();
        
        
        for(int x = 0; x < jumlahRow; x++) {

            String kolomNamaBarang = tabelTransaksi.getValueAt(x, 0).toString();
            String kolomIdBarang = tabelTransaksi.getValueAt(x, 1).toString();
            int kolomHarga = Integer.parseInt(tabelTransaksi.getValueAt(x, 2).toString());
            int kolomQty = Integer.parseInt(tabelTransaksi.getValueAt(x, 3).toString());
            int kolomSubtotal = Integer.parseInt(tabelTransaksi.getValueAt(x, 4).toString());
            
//            String sql = "INSERT INTO transaksiDetail (namaBarang, harga, qty, subtotal) VALUES ('"
//                +hasil[x][0]+"','"+hasil[x][1]+"','"+hasil[x][2]+"','"+hasil[x][3]+"')";  

            String sql = "INSERT INTO ordersDetail (idTransaksi, namaBarang, idBarang, harga, qty, subtotal) VALUES ('"
                +idTransaksi+"','"
                +kolomNamaBarang+"','"+kolomIdBarang+"','"+kolomHarga+"','"+kolomQty+"','"+kolomSubtotal+"')"; 
            
            
          PreparedStatement eksekusi;
            try {
                eksekusi = KonfigurasiDatabase.getKoneksi().prepareStatement(sql);
                eksekusi.execute();
                eksekusi.close();
            } catch (SQLException ex) {
                System.err.print(ex);
                JOptionPane.showMessageDialog(this, "Data Gagal Disimpan:" + ex);
                return;
            }
          
          
        }
                JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan", "Sukses!", INFORMATION_MESSAGE);

                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                totalBayarTF.setText("0");
                namaBarangTF.setText("");
                hargaBarangTF.setText("");
                idBarangTF.setText("");
                qtyBeliTF.setValue(1);
                idPelanggan.setText("");
                namaPelanggan.setText("");
                alamatPelanggan.setText("");
                noHpPelanggan.setText("");
                jenisKelaminPelanggan.setText("");
                uangBayarTF.setText("");
                cariDataPelangganBT.setEnabled(true);


    }//GEN-LAST:event_prosesTransaksiBTMouseClicked

    private void namaPelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaPelangganKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPelangganKeyPressed

    private void tambahBarangBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBarangBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahBarangBTActionPerformed

    private void batalTransaksiBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batalTransaksiBTMouseClicked
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        totalBayarTF.setText("0");
        namaBarangTF.setText("");
        hargaBarangTF.setText("");
        idBarangTF.setText("");
        qtyBeliTF.setValue(1);
        idPelanggan.setText("");
        namaPelanggan.setText("");
        alamatPelanggan.setText("");
        noHpPelanggan.setText("");
        jenisKelaminPelanggan.setText("");
        uangBayarTF.setText("");
        cariDataPelangganBT.setEnabled(true);
        
    }//GEN-LAST:event_batalTransaksiBTMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void batalTransaksiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalTransaksiBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batalTransaksiBTActionPerformed

    private void cariDataPelangganBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariDataPelangganBTActionPerformed
        ViewListDataPelanggan vLDP = new ViewListDataPelanggan(this);
        vLDP.setVisible(true);
    }//GEN-LAST:event_cariDataPelangganBTActionPerformed

    private void totalBayarTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBayarTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBayarTFActionPerformed

    private void batalTransaksiBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batalTransaksiBTMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_batalTransaksiBTMouseEntered

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewPelangganInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewPelangganInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewPelangganInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewPelangganInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new ViewTransaksi().setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatPelanggan;
    private javax.swing.JButton batalTransaksiBT;
    private javax.swing.JButton cariDataPelangganBT;
    private javax.swing.JTextField hargaBarangTF;
    private javax.swing.JTextField idBarangTF;
    private javax.swing.JTextField idPelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jenisKelaminPelanggan;
    private javax.swing.JLabel jofewfwrw;
    private javax.swing.JTextField namaBarangTF;
    private javax.swing.JTextField namaPelanggan;
    private javax.swing.JTextField noHpPelanggan;
    private javax.swing.JButton prosesTransaksiBT;
    private javax.swing.JSpinner qtyBeliTF;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JButton tambahBarangBT;
    private javax.swing.JTextField totalBayarTF;
    private javax.swing.JTextField uangBayarTF;
    // End of variables declaration//GEN-END:variables


}

 
